# https://pixi.sh/latest/ide_integration/readthedocs/

version: 2

sphinx:
   configuration: docs/conf.py

build:
   os: ubuntu-24.04
   tools:
      python: "3.13"
   jobs:
      pre_install:
         - curl -fsSL https://pixi.sh/install.sh | bash
         - export PATH="/home/docs/.pixi/bin:$PATH"
      install:
         - pixi run -e docs sphinx-build -b html docs $READTHEDOCS_OUTPUT/html
